// Generated by CoffeeScript 1.7.1
(function() {
  var new_excuse, square;

  square = function(x) {
    return x * x;
  };

  new_excuse = function() {
    return "I'm sick";
  };

  jQuery(function() {
    $("#instructions").html("foo");
    return $("html").click(function() {
      return alert(new_excuse());
    });
  });

}).call(this);
