// Generated by CoffeeScript 1.4.0
(function() {
  var excuses, new_excuse;

  excuses = ["I'm sick", "My car won't start"];

  new_excuse = function() {
    if (Math.random() < 0.5) {
      return excuses[0];
    } else {
      return excuses[1];
    }
  };

  jQuery(function() {
    $("#instructions").html("Click for an excuse");
    return $("html").click(function() {
      $("#instructions").html("");
      return $("#excuses").html($("#excuses").html() + '<div class="bubble">' + new_excuse() + '</div>');
    });
  });

}).call(this);
